eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8900
spring:
  application:
    name: service-security-zuul
#路由分发
zuul:
  routes:
    service-hi:
      path: /service/hi/**
      serviceId: SERVICE-HI
      stripPrefix: false
    service-order:
      path: /service/order/**
      serviceId: SERVICE-ORDER
      stripPrefix: false

jwt:
  secret: and0